version: '3.8'
services:
  app:
    build: .
    depends_on:
      - redis
    ports:
      - "8080:8080"
    network_mode: host

  redis:
    image: redis:7.0
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
